client:
  # url of server
  url: http://localhost:8000
  
#telegram:
#  apiToken: (string) your telegram api token from bot father
#  webhookUrl: (string) example service for webhooks - ngrok

postgreDatabase:
  host: ec2-44-194-54-186.compute-1.amazonaws.com
  port: 5432
  username: tkbiyuywcczfsd
  dbname:  d5ikvg4dou3e5f
  sslmode: enabled

redisDatabase:
  host: redis-18074.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
  port: 18074
  password: 2nw6DVEssHfAh4SEpCGtlTKu3jTJb9Dv

kraken:
  apiurl: url

krakenWS:
  requests:
    writeWaitInSeconds: 10
    pongWaitInSeconds: 60
    pingPeriodInSeconds: 10
    maxMessageSize: 512
  kraken:
    wsapiurl: url
