client:
  # url of server
  url: http://localhost:8000
  
#telegram:
#  apiToken: (string) your telegram api token from bot father
#  webhookUrl: (string) example service for webhooks - ngrok

postgreDatabase:
  host: ec2-44-194-54-186.compute-1.amazonaws.com
  port: 5432
  username: tkbiyuywcczfsd
  dbname:  d5ikvg4dou3e5f
  sslmode: disabled

redisDatabase:
  host: ec2-34-192-8-209.compute-1.amazonaws.com
  port: 20810
  password: pa9a2100753e15116a424cdc9f7d960dcabdbcbdf5b5173718b85da33216f55b6

kraken:
  apiurl: (string)

krakenWS:
  requests:
    writeWaitInSeconds: (int) 10 by default
    pongWaitInSeconds: (int) 60 by default
    pingPeriodInSeconds: (int) 10 by default
    maxMessageSize: (int) 512 by default
  kraken:
    wsapiurl: (string)
